// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scene4-layouts/BottomThird.tsx": () => import("../components/mockups/scene4-layouts/BottomThird.tsx"),
  "./components/mockups/scene4-layouts/SplitWeight.tsx": () => import("../components/mockups/scene4-layouts/SplitWeight.tsx"),
  "./components/mockups/scene4-layouts/WordStack.tsx": () => import("../components/mockups/scene4-layouts/WordStack.tsx")
};
